services:
  dev:
    build: ./docker
    volumes:
      - ./.ssh:/root/.ssh
      - ./.vscode-server:/root/.vscode-server
      - ./.vscode:/root/linux/.vscode
      - ./benchmarks:/root/benchmarks
      - ./linux:/root/linux
      - ./linux_configs:/root/linux_configs
      - ./images:/root/images
      - ./scripts:/root/scripts
      - ./vm_hw1_files:/root/vm_hw1_files
      - ./vm_hw2_files:/root/vm_hw2_files
