version: "3.9"
services:
  dev:
    build:
      context: ./docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: ${UID:-1000}
    volumes:
      - .:/workspace
      - ./.ssh/id_ed25519:/etc/ssh/ssh_host_ed25519_key
      - ./.ssh/id_ed25519.pub:/etc/ssh/ssh_host_ed25519_key.pub
    cap_add:
      - SYS_PTRACE  # for debugger to attach running process
