services:
  hw1:
    build: ./docker
    volumes:
      - ./.ssh:/root/.ssh
      - ./.vscode:/root/linux/.vscode
      - ./linux:/root/linux
      - ./qemu:/root/qemu
      - ./images:/root/images
      - ./vm_hw1_files:/root/vm_hw1_files:ro
